;;;; package.lisp

(defpackage #:selenium
  (:use #:cl #:drakma)
  (:export #:session-start
	   #:session-stop
	   #:open-page
	   #:type-string
	   #:click
	   #:start-test
	   #:wait-for-page-to-load
	   #:double-click
	   #:context-menu
	   #:fire-event
	   #:focus
	   #:key-press
	   #:shif-key-down
	   #:shif-key-up
	   #:meta-key-down
	   #:meta-key-up
	   #:alt-key-down
	   #:alt-key-up
	   #:control-key-down
	   #:control-key-up
	   #:key-down
	   #:key-up
	   #:mouse-over
	   #:mouse-out
	   #:mouse-down
	   #:mouse-down-right
	   #:mouse-up
	   #:mouse-up-right
	   #:mouse-move
	   #:type-keys
	   #:set-speed
	   #:get-speed
	   #:check
	   #:uncheck
	   #:select
	   #:add-selection
	   #:remove-selection
	   #:remove-all-selections
	   #:submit
	   #:open-window
	   #:select-window
	   #:select-pop-up
	   #:deselect-pop-up
	   #:select-frame
	   #:wait-for-pop-up
	   #:choose-cancel-on-next-confirmation
	   #:choose-ok-on-next-confirmation
	   #:answer-on-next-prompt
	   #:go-back
	   #:refresh
	   #:close-pop-up
	   #:alert-present?
	   #:prompt-present?
	   #:confirmation-present?
	   #:get-prompt
	   #:get-confirmation
	   #:get-alert
	   #:get-location
	   #:get-title
	   #:get-body-text
	   #:get-value
	   #:get-text
	   #:highlight
	   #:get-eval
	   #:checked?
	   #:get-table
	   #:get-selected-labels
	   #:get-selected-label
	   #:get-selected-values
	   #:get-selected-value
	   #:get-selected-indexes
	   #:get-selected-index
	   #:get-selected-ids
	   #:get-selected-id
	   #:something-selected?
	   #:get-select-options
	   #:get-attribute
	   #:text-present?
	   #:element-present?
	   #:visible?
	   #:editable
	   #:get-all-buttons
	   #:get-all-links
	   #:get-all-fields
	   #:get-attribute-from-all-windows
	   #:dragdrop
	   #:set-mouse-speed
	   #:get-mouse-speed
	   #:drag-and-drop
	   #:drag-and-drop-to-object
	   #:window-focus
	   #:window-maximize
	   #:get-all-window-ids
	   #:get-all-window-names
	   #:get-all-window-titles
	   #:get-html-source
	   #:set-cursor-position
	   #:get-element-index
	   #:ordered?
	   #:get-element-position-left
	   #:get-element-position-top
	   #:get-element-width
	   #:get-element-height
	   #:get-cursor-position
	   #:get-expression
	   #:get-xpath-count
	   #:assign-id
	   #:allow-native-xpath
	   #:ignore-attributes-without-value
	   #:wait-for-condition
	   #:set-timeout
	   #:wait-for-frame-to-load
	   #:get-cookie
	   #:get-cookie-by-name
	   #:cookie-present?
	   #:create-cookie
	   #:delete-cookie
	   #:delete-all-visible-cookies
	   #:set-browser-log-level
	   #:run-script
	   #:add-location-strategy
	   #:capture-page-screenshot
	   #:rollup
	   #:add-script
	   #:remove-script
	   #:use-xpath-library
	   #:set-context
	   #:attach-file
	   #:capture-screenshot
	   #:capture-screenshot-to-string
	   #:capture-network-traffic
	   #:add-custom-request-header
	   #:capture-page-screenshot-to-string
	   #:shutdown-selenium-server
	   #:retrieve-last-remote-control-logs
	   #:key-down-native
	   #:key-up-native
	   #:key-press-native))

(in-package :selenium)